import {test,expect} from '@playwright/test';
import {mkdir} from 'node:fs/promises';
const input=async page=>page.getByRole('tab',{name:'Inserisci una posizione'}).click();
const set=async(page,frets)=>{for(let i=0;i<6;i++)await page.getByRole('combobox',{name:`Tasto corda ${6-i}`,exact:true}).selectOption(frets[i]===null?'x':String(frets[i]));};
for(const width of [1440,390,320])test(`Input, stati, focus e layout ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/tools/set-class-explorer');
 await expect(page.getByRole('tab',{name:'Esplora',exact:true})).toHaveAttribute('aria-selected','true');
 const before=await page.locator('#sce-explore').innerText();await input(page);
 await expect(page.getByTestId('set-input-frets')).toBeFocused();await expect(page.getByRole('button',{name:'Apri questa set class in Esplora'})).toBeDisabled();
 await set(page,[null,3,2,0,1,0]);await expect(page.getByTestId('set-input-analysis')).toHaveAttribute('data-forte','3-11');await expect(page.getByTestId('set-input-counts')).toHaveText('5 note suonate · 3 classi distinte · raddoppi presenti');await expect(page.getByTestId('set-input-pitches')).toHaveAttribute('data-pitches','48,52,55,60,64');
 await page.getByRole('tab',{name:'Esplora',exact:true}).click();expect(await page.locator('#sce-explore').innerText()).toBe(before);await input(page);await expect(page.getByTestId('set-input-frets')).toHaveText('× · 3 · 2 · 0 · 1 · 0');
 const board=page.locator('#sce-input .guitar-board');await board.focus();await page.keyboard.press('ArrowRight');await page.getByRole('button',{name:'Corda 1, tasto 12, E5',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('combobox',{name:'Tasto corda 1',exact:true})).toHaveValue('12');await page.getByRole('button',{name:'Corda 1 muta',exact:true}).click();await expect(page.getByRole('combobox',{name:'Tasto corda 1',exact:true})).toHaveValue('x');
 await set(page,[null,3,2,0,1,0]);await page.getByRole('button',{name:'Apri questa set class in Esplora'}).click();await expect(page.getByRole('tab',{name:'Esplora',exact:true})).toHaveAttribute('aria-selected','true');await input(page);await expect(page.getByTestId('set-input-pitches')).toHaveAttribute('data-pitches','48,52,55,60,64');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await mkdir('/tmp/set-class-input-preview',{recursive:true});await page.screenshot({path:`/tmp/set-class-input-preview/manual-${width}.png`,fullPage:true});await page.getByRole('tab',{name:'Esplora',exact:true}).click();await page.getByRole('button',{name:/Osserva corda 1, tasto 0/}).first().click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`/tmp/set-class-input-preview/explore-${width}.png`,fullPage:true});await input(page);
 await set(page,[0,null,null,null,null,0]);await expect(page.getByTestId('set-input-analysis')).toHaveAttribute('data-forte','');await expect(page.getByTestId('set-input-analysis')).toHaveAttribute('data-prime','0');await expect(page.getByTestId('set-input-counts')).toContainText('2 note suonate · 1 classe distinta');await expect(page.getByRole('button',{name:'Apri questa set class in Esplora'})).toBeDisabled();
 await page.getByRole('button',{name:'Svuota posizione'}).click();await expect(page.getByRole('combobox',{name:'Tasto corda 6',exact:true})).toBeFocused();await expect(page.getByTestId('set-input-analysis')).toHaveCount(0);expect(errors).toEqual([]);
});
test('Esplora: osservazione, filtri separati e trasferimento soltanto esplicito',async({page})=>{
 await page.goto('/tools/set-class-explorer');await input(page);await set(page,[null,3,5,4,5,null]);await page.getByRole('button',{name:'Apri questa set class in Esplora'}).click();await expect(page.locator('.hero-summary-item').first()).toContainText('4-20');
 await page.getByRole('button',{name:'Tn',exact:true}).click();await page.getByRole('button',{name:'2',exact:true}).click();await page.getByRole('button',{name:'Voicing',exact:true}).click();await page.getByRole('checkbox',{name:'Exclude open strings',exact:true}).check();const url=page.url();await input(page);await expect(page.getByTestId('set-input-frets')).toHaveText('× · 3 · 5 · 4 · 5 · ×');await page.getByRole('tab',{name:'Esplora',exact:true}).click();expect(page.url()).toBe(url);await expect(page.getByRole('checkbox',{name:'Exclude open strings',exact:true})).toBeChecked();
 await page.getByRole('button',{name:/Osserva corda 1, tasto 0/}).first().click();await expect(page.locator('.sce-inspection').first()).toContainText('non una nota aggiunta');expect(await page.locator('.fretboard__cell.is-observed').count()).toBeGreaterThan(1);
 await page.getByRole('button',{name:'Original',exact:true}).click();await page.getByRole('button',{name:'Voicing',exact:true}).click();const copy=page.getByRole('button',{name:'Usa questa posizione come input'}).first();await expect(copy).toBeVisible();const physical=await copy.locator('..').locator('.fretboard__cell').filter({has:page.locator('.fretboard__marker.is-active')}).evaluateAll(cells=>cells.map(c=>c.getAttribute('aria-label').match(/corda (\d), tasto (\d+)/).slice(1).map(Number)));
await copy.click();for(const [s,f] of physical)await expect(page.getByRole('combobox',{name:`Tasto corda ${s}`,exact:true})).toHaveValue(String(f));await expect(page.getByRole('tab',{name:'Inserisci una posizione'})).toHaveAttribute('aria-selected','true');await expect(page.getByTestId('set-input-counts')).toContainText('4 note suonate · 4 classi distinte');await expect(page.getByTestId('set-input-analysis')).toHaveAttribute('data-forte','4-20');
 await page.getByRole('tab',{name:'Esplora',exact:true}).click();await page.getByRole('combobox',{name:'Forte tetrachord',exact:true}).selectOption('4-1');await input(page);await expect(page.getByTestId('set-input-analysis')).toHaveAttribute('data-forte','4-20');
});
test('Cardinalità 2, 5 e 6; altezze incrociate; apertura della famiglia corretta',async({page})=>{
 await page.goto('/tools/set-class-explorer');await input(page);
 for(const [frets,card] of [[[0,null,null,null,0,null],2],[[0,0,0,0,0,0],5],[[0,0,0,0,0,1],6]]){await set(page,frets);await expect(page.getByTestId('set-input-counts')).toContainText(`${card} classi distinte`);if(card>=3){await page.getByRole('button',{name:'Apri questa set class in Esplora'}).click();await expect(page.getByRole('button',{name:card===5?'Pentachords':'Hexachords',exact:true})).toHaveAttribute('aria-pressed','true');await input(page);}}
 await set(page,[null,10,0,1,0,null]);await expect(page.getByTestId('set-input-pitches')).toHaveAttribute('data-pitches','50,55,56,59');await expect(page.getByTestId('set-input-pitches')).toHaveAttribute('data-strings','4,5,3,2');await page.getByText('Calcolo, raddoppi e limiti',{exact:true}).click();await expect(page.locator('.sce-details')).toContainText('invertita');
});
for(const width of [1920,390,320])test(`24 tasti, salvataggio e recupero ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000});await page.goto('/tools/set-class-explorer');await input(page);
 await set(page,[null,15,14,12,13,24]);await expect(page.getByTestId('set-input-pitches')).toHaveAttribute('data-pitches','60,64,67,72,88');await expect(page.getByTestId('set-input-analysis')).toHaveAttribute('data-forte','3-11');
 await page.getByRole('button',{name:'Corda 1, tasto 24, E6',exact:true}).focus();await page.keyboard.press('Space');await expect(page.getByRole('combobox',{name:'Tasto corda 1',exact:true})).toHaveValue('x');await page.keyboard.press('Enter');await expect(page.getByRole('combobox',{name:'Tasto corda 1',exact:true})).toHaveValue('24');
 await page.reload();await expect(page.getByRole('tab',{name:'Inserisci una posizione'})).toHaveAttribute('aria-selected','true');await expect(page.getByTestId('set-input-frets')).toHaveText('× · 15 · 14 · 12 · 13 · 24');await expect(page.getByTestId('set-input-frets')).toBeFocused();
 await page.getByRole('button',{name:'Apri questa set class in Esplora'}).click();await expect(page.locator('.hero-summary-item').first()).toContainText('3-11');await expect(page.locator('.sce-explore-limit')).toContainText('0–12');await page.reload();await expect(page.getByRole('tab',{name:'Esplora',exact:true})).toHaveAttribute('aria-selected','true');await input(page);await expect(page.getByTestId('set-input-pitches')).toHaveAttribute('data-pitches','60,64,67,72,88');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 if(width===1920){const sizes=await page.locator('#sce-input .guitar-board').evaluate(el=>({container:el.getBoundingClientRect().width,diagram:el.firstElementChild.getBoundingClientRect().width}));expect(sizes.container).toBeLessThanOrEqual(sizes.diagram+3);expect(sizes.container).toBeGreaterThan(900);}
 await page.getByRole('button',{name:'Corda 5, tasto 15, C4',exact:true}).focus();await page.screenshot({path:`/tmp/set-class-input-preview/extended-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'Svuota posizione'}).click();expect(await page.evaluate(()=>localStorage.getItem('gtl.set-class.position.v1'))).toBeNull();await expect(page.getByRole('combobox',{name:'Tasto corda 6',exact:true})).toBeFocused();await page.reload();await expect(page.getByTestId('set-input-counts')).toHaveText('0 note suonate · 0 classi distinte');
});
test('Dati locali malformati non bloccano il tool',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('gtl.set-class.position.v1',JSON.stringify({version:1,frets:[25,0,0,0,0,0]}));localStorage.setItem('gtl.set-class.mode.v1','non-valid');});await page.goto('/tools/set-class-explorer');await expect(page.getByRole('tab',{name:'Esplora',exact:true})).toHaveAttribute('aria-selected','true');await input(page);await expect(page.getByTestId('set-input-counts')).toHaveText('0 note suonate · 0 classi distinte');await set(page,[24,null,null,null,null,null]);await expect(page.getByTestId('set-input-counts')).toContainText('1 nota suonata · 1 classe distinta');
});
